stages:
  validate:
    cmd: python src/validate_data.py
    deps:
      - src/validate_data.py
      - data/raw
      - params.yaml
    outs:
      - metrics/validation.ok:
          cache: false
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
      - params.yaml
    outs:
      - models
    metrics:
      - metrics/leaderboard.csv:
          cache: false
      - metrics/metrics.json:
          cache: false

  predict_existing:
    cmd: python src/predict_existing.py
    deps:
      - src/predict_existing.py
      - data/processed/X_val.csv
      - data/processed/y_val.csv
      - models
    outs:
      - metrics/preds_val

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - metrics/metrics.json
      - params.yaml
    metrics:
      - metrics/decision.json:
          cache: false

  evidently:
    cmd: python src/evidently_report.py
    deps:
      - src/evidently_report.py
      - data/processed/X_train.csv
      - data/processed/X_val.csv
    outs:
      - metrics/reports

  tune:
    cmd: python src/tune.py
    deps:
      - src/tune.py
      - data/processed
      - params.yaml
      - metrics/metrics.json
    metrics:
      - metrics/tuned_metrics.json:
          cache: false

  alert:
    cmd: python src/alerting.py
    deps:
      - src/alerting.py
      - metrics/decision.json