version: '3.9'
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    environment:
      - BACKEND_URI=sqlite:////mlflow/mlflow.db
      - ARTIFACT_ROOT=/mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

volumes:
  mlflow_data:


